# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  process_checkins:
    class: "ProcessCheckinsJob"
    queue: default
    schedule: every 60 minutes
  cleanup_expired_tokens:
    class: "CleanupExpiredTokensJob"
    queue: default
    schedule: every day at 3am
  cleanup_audit_logs:
    class: "CleanupAuditLogsJob"
    queue: default
    schedule: every day at 4am
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
